### PR TITLE
Introduced note->link feature request (#12)

### PR DESCRIPTION
**Pull request by acer123acer123**
Implemented feature documented in #12. If the note is a valid-formatted URL then it will be converted to a URL during the build phase.

### CODE REVIEW

**Comment by darekkay** [comment]
Thanks Chris, the solution looks good 👍 

Just two remarks: could you please:

1. ... fix the ESLint errors (see [Travis output](https://travis-ci.com/github/darekkay/static-marks/jobs/395866828)). Running `yarn lint:fix` or `npm run link:fix` should fix most of the issues. I consider the `no-new` error a valid use case, so you can ignore this issue by adding the following line before `new URL`:

```
// eslint-disable-next-line no-new
```

2. ... adjust the existing test case by adding an example `http*` entry [here](https://github.com/darekkay/static-marks/blob/196ee89255058260bd376e33caeafd8db193928a/test/transform-json.test.js#L21) and adjusting the `expected` array accordingly?

**Comment by acer123acer123** [comment]
I’m working on that as we speak.  Thanks!

**Comment by acer123acer123** [comment]
I have #1 complete (not yet committed) but I need a hint for #2. I’m not a developer by trade (I’m a DevOps Consultant Engineer at Progressive). I work very closely with developers but my skillset is around architecture, CI/CD, etc. I’ve written applications and learned languages as needed.  So, for this one, I am learning JavaScript (I’ve never really messed with it in any kind of depth). Can you point me to the testing tool you are using so that I can run it manually on my local machine before committing the changes?
Thanks

**Comment by acer123acer123** [comment]
Never mind. I figured it out by looking at a successful Travis build.

From: Chris Ryan <christopher.ryan@gmail.com>
Date: Tuesday, October 6, 2020 at 8:36 AM
To: darekkay/static-marks <reply@reply.github.com>, darekkay/static-marks <static-marks@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: Re: [darekkay/static-marks] Introduced note->link feature request (#12) (#16)

I have #1 complete (not yet committed) but I need a hint for #2. I’m not a developer by trade (I’m a DevOps Consultant Engineer at Progressive). I work very closely with developers but my skillset is around architecture, CI/CD, etc. I’ve written applications and learned languages as needed.  So, for this one, I am learning JavaScript (I’ve never really messed with it in any kind of depth). Can you point me to the testing tool you are using so that I can run it manually on my local machine before committing the changes?
Thanks

**Comment by darekkay** [comment]
@acer123acer123 Thanks, looks good now 😃 I've seen you have figured it out already, but here's just a small tip. In JavaScript projects, you will almost always find a `package.json` file, where all `scripts` are defined. There are often scripts called `test` (= unit tests) and `lint` (= code quality and project guidelines), which you can run with `npm run <script>` or `yarn <script>`. This way, developers don't have to care which libraries/tools are actually being used for which project.

**Comment by darekkay** [comment]
@all-contributors please add @acer123acer123 to maintenance

**Pull request merged**
