### PR TITLE
Implements #8

### PR DESCRIPTION
**Pull request by jflip**
My first implementation of duplicate link checking

Please let me know if there are any issues at all, happy to learn 👍 

Fixes: #8

### CODE REVIEW

**Comment by jflip** [comment]
If accepted would you mind labelling this as "hacktoberfest-accepted"? Just helps with the new rules for Hacktoberfest 2020. I would really appreciate it :)

https://dev.to/jimcmorrison/hacktoberfest-2020-rule-updates-147p

**Comment by jflip** [comment]
Ah I've gone and committed the package-lock,json, what would be the best way to resolve?

**Review by darekkay — APPROVED** [review]
Looks good and works as expected, thanks!

**Comment by darekkay** [comment]
@all-contributors please add @jflip to maintenance

**Pull request merged**
